"""So sánh output thuật toán Stripe token (caesar/stripe_encode/js_checksum
/rv_timestamp) — sinh giá trị reference Python để hardcode vào unit test Rust.

Chạy: python3 test/check_stripe_token_parity.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT.parent))


def main() -> int:
    # Import từ module Python repository
    from gpt_signup_hybrid.stripe_token import (
        caesar_shift,
        stripe_encode,
        compute_js_checksum,
        compute_rv_timestamp,
        StripeTokenConfig,
    )

    cases: list[tuple[str, str]] = []

    # Caesar shift
    cases.append((
        "caesar_shift('Hello', 11)",
        caesar_shift("Hello", 11),
    ))
    cases.append((
        "caesar_shift('abc XYZ 123', 11)",
        caesar_shift("abc XYZ 123", 11),
    ))
    cases.append((
        "caesar_shift('!@#$%', 5)",
        caesar_shift("!@#$%", 5),
    ))

    # Stripe encode
    cases.append((
        "stripe_encode('test')",
        stripe_encode("test"),
    ))
    cases.append((
        "stripe_encode('{\"id\":\"abc\"}')",
        stripe_encode('{"id":"abc"}'),
    ))
    cases.append((
        "stripe_encode('hello world!')",
        stripe_encode("hello world!"),
    ))

    # js_checksum
    cases.append((
        "compute_js_checksum('test_ppage_id_abc', shift=11)",
        compute_js_checksum("test_ppage_id_abc", shift=11),
    ))
    cases.append((
        "compute_js_checksum('pp_xyz_123', shift=11)",
        compute_js_checksum("pp_xyz_123", shift=11),
    ))

    # rv_timestamp
    cfg = StripeTokenConfig(
        bundle_hash="dummy",
        shift=11,
        rv_ts="2024-01-01 00:00:00 -0000",
        rv="e5ebd5e1e6abc123",
        sv="3c7ef39815def456",
    )
    cases.append((
        "compute_rv_timestamp(<canonical config>)",
        compute_rv_timestamp(cfg),
    ))

    print("# stripe_token parity reference values")
    print("# Generated by test/check_stripe_token_parity.py — paste vào unit test Rust")
    print()
    for label, value in cases:
        print(f"# {label}")
        print(f"#   = {value!r}")
        print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
