"""Build orchestrator cho GSH Windows exe.

Chạy trên Windows runner (CI hoặc máy local). Không cross-compile từ Mac/Linux.

Usage:
    python scripts/build_exe.py --hours 24
    python scripts/build_exe.py --expires-at 1767225600   # explicit unix ts
    python scripts/build_exe.py                            # default 999999999999

Pipeline:
    1. Generate ``_expire_const.py`` từ args.
    2. (CI step) ``playwright install chromium`` chạy trước khi gọi script này.
    3. Copy Chromium từ ``%LOCALAPPDATA%\\ms-playwright\\chromium-*`` vào
       ``playwright-browsers/`` để PyInstaller bundle.
    4. Chạy PyInstaller với ``scripts/gsh.spec``.
    5. Output: ``dist/GSH.exe``.

Sau bước này, ``scripts/installer.iss`` được Inno Setup compile thành
``dist/GSH-Setup.exe`` (xem workflow CI).
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

# Force UTF-8 stdout/stderr trên Windows — default cp1252 không encode được
# unicode chars (vd '->', '*', emoji). Phòng trường hợp print log có
# unicode (lib khác có thể inject) → crash console writer.
if sys.platform.startswith("win"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:  # noqa: BLE001 — stdio reconfigure best-effort
        pass

DEFAULT_HOURS = 24  # Default valid window khi không truyền --hours / --expires-at
PROJECT_ROOT = Path(__file__).resolve().parent.parent


def _generate_expire_const(build_time: int, expires_at: int) -> Path:
    """Generate ``_expire_const.py`` cạnh package root. PyInstaller spec sẽ
    pickup file này qua ``datas`` rule.
    """
    out = PROJECT_ROOT / "_expire_const.py"
    body = (
        '"""AUTO-GENERATED by scripts/build_exe.py. DO NOT EDIT."""\n'
        '# Build time + expire time đều unix timestamp (UTC seconds).\n'
        '# _expire_check.enforce_expiry() đọc 2 hằng này.\n'
        f"BUILD_TIME = {int(build_time)}\n"
        f"EXPIRES_AT = {int(expires_at)}\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def _bundle_playwright_browsers() -> bool:
    """Copy Chromium từ %LOCALAPPDATA%\\ms-playwright sang
    ``playwright-browsers/`` cạnh project root. Trả True nếu copy thành công.

    Bỏ qua nếu folder source không tồn tại — caller (CI) sẽ chạy
    ``playwright install chromium`` trước khi gọi script này.
    """
    if sys.platform.startswith("win"):
        local_appdata = os.environ.get("LOCALAPPDATA")
        if not local_appdata:
            print("[build] LOCALAPPDATA missing -- skip Chromium bundle", flush=True)
            return False
        src_root = Path(local_appdata) / "ms-playwright"
    else:
        # Mac/Linux fallback path để dev test (không build được Win exe)
        src_root = Path.home() / ".cache" / "ms-playwright"
        if not src_root.exists():
            src_root = Path.home() / "Library" / "Caches" / "ms-playwright"

    if not src_root.is_dir():
        print(f"[build] Chromium source not found at {src_root} -- "
              f"chạy `playwright install chromium` trước", flush=True)
        return False

    # Tìm chromium-* và ffmpeg-* (Playwright cần ffmpeg cho video record).
    dest = PROJECT_ROOT / "playwright-browsers"
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True, exist_ok=True)

    copied_any = False
    for child in src_root.iterdir():
        if not child.is_dir():
            continue
        # Chỉ pick chromium + ffmpeg, bỏ firefox/webkit để giảm size.
        if child.name.startswith(("chromium-", "chromium_headless_shell-", "ffmpeg-")):
            shutil.copytree(child, dest / child.name)
            print(f"[build] bundled {child.name}", flush=True)
            copied_any = True

    if not copied_any:
        print(f"[build] no chromium found under {src_root}", flush=True)
        shutil.rmtree(dest)
        return False
    return True


def _run_pyinstaller(spec: Path) -> int:
    """Chạy PyInstaller với spec. Trả exit code."""
    env = os.environ.copy()
    # Spec đọc PROJECT_ROOT từ env này — KHÔNG dùng __file__ vì PyInstaller
    # eval spec ở context khác.
    env["GSH_BUILD_ROOT"] = str(PROJECT_ROOT)
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--clean",
        "--noconfirm",
        "--workpath", str(PROJECT_ROOT / "build"),
        "--distpath", str(PROJECT_ROOT / "dist"),
        str(spec),
    ]
    print(f"[build] {' '.join(cmd)}", flush=True)
    return subprocess.call(cmd, env=env)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build GSH Windows exe with optional expire date.",
    )
    grp = parser.add_mutually_exclusive_group()
    grp.add_argument(
        "--hours",
        type=float,
        default=None,
        help=f"Số giờ valid kể từ build time. Default = {DEFAULT_HOURS}h. "
             "Vd: --hours 48.",
    )
    grp.add_argument(
        "--expires-at",
        type=int,
        default=None,
        help="Explicit unix timestamp UTC (UTC seconds). Override --hours. "
             "Vd: --expires-at 1767225600.",
    )
    grp.add_argument(
        "--never-expire",
        action="store_true",
        help="Build exe không có expire (BUILD_TIME hợp lệ, EXPIRES_AT = "
             "999999999999 ~ năm 33658). Chỉ dùng cho dev/internal.",
    )
    parser.add_argument(
        "--no-bundle-chromium",
        action="store_true",
        help="Skip copy Chromium vào exe (exe chỉ ~80 MB, lần đầu chạy "
             "Playwright sẽ download).",
    )
    parser.add_argument(
        "--skip-pyinstaller",
        action="store_true",
        help="Chỉ generate _expire_const.py + bundle Chromium, không chạy "
             "PyInstaller (debug).",
    )
    args = parser.parse_args()

    build_time = int(time.time())

    if args.expires_at is not None:
        expires_at = args.expires_at
    elif args.never_expire:
        expires_at = 999_999_999_999  # year 33658
    elif args.hours is not None:
        expires_at = build_time + int(args.hours * 3600)
    else:
        expires_at = build_time + DEFAULT_HOURS * 3600  # default 24h

    # Sanity
    if expires_at <= build_time:
        print(
            f"[build] FAIL: expires_at ({expires_at}) <= build_time "
            f"({build_time}) -- exe se expired ngay khi tao.",
            file=sys.stderr,
        )
        return 1

    expire_path = _generate_expire_const(build_time, expires_at)
    print(
        f"[build] generated {expire_path.name}: "
        f"BUILD_TIME={build_time} EXPIRES_AT={expires_at} "
        f"(valid {(expires_at - build_time) / 3600:.2f} hours)",
        flush=True,
    )

    if not args.no_bundle_chromium:
        _bundle_playwright_browsers()

    if args.skip_pyinstaller:
        print("[build] --skip-pyinstaller set, exit early", flush=True)
        return 0

    spec = PROJECT_ROOT / "scripts" / "gsh.spec"
    rc = _run_pyinstaller(spec)
    if rc != 0:
        print(f"[build] PyInstaller failed rc={rc}", file=sys.stderr)
        return rc

    out_exe = PROJECT_ROOT / "dist" / "GSH.exe"
    if sys.platform.startswith("win") and not out_exe.is_file():
        print(f"[build] FAIL: expected output {out_exe} not found", file=sys.stderr)
        return 1

    if out_exe.is_file():
        size_mb = out_exe.stat().st_size / 1_048_576
        # ASCII '->' thay vì '→' — Windows console default cp1252 không
        # encode được U+2192 → crash UnicodeEncodeError.
        print(f"[build] OK -> {out_exe} ({size_mb:.1f} MB)", flush=True)

    return 0


if __name__ == "__main__":
    sys.exit(main())
